


variables:
  REGISTRY: "dockerreg.planck.security"
  DEBIAN: "corev3-debian"
  #previous version used to speed up docker build (using cache and such)
  PREVIOUS_VERSION: "1.0"
  VERSION: "2.0"
  


stages:
  - docker
  - test
  - release



debian-docker:
  stage: docker
  tags:
    - docker
  variables:
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_TLS_CERT: ""
    DOCKER_BUILDKIT: 1
  image: docker:23.0.6
  services:
    - docker:23.0.6-dind
  retry:
    max: 2
    when: [runner_system_failure, unknown_failure, stuck_or_timeout_failure]
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        paths: [docker/debian/*]
        compare_to: master
  script:
    - docker login -u ${PLANCK_DOCKER_REGISTRY_USER} -p ${PLANCK_DOCKER_REGISTRY_PASSWORD} ${REGISTRY}
    - docker pull ${REGISTRY}/${DEBIAN}:${PREVIOUS_VERSION} || true
    - docker build
      --network=host
      --cache-from ${DEBIAN}:${PREVIOUS_VERSION}
      -t ${REGISTRY}/${DEBIAN}:${VERSION}
      -f docker/debian/Dockerfile
      .
    - docker push ${REGISTRY}/${DEBIAN}:${VERSION}
  rules:
    - changes:
    # Only run this job when the Dockerfile is modified
        - docker/debian/Dockerfile

debian-test:
  stage: test
  tags: [ linux ]
  image: ${REGISTRY}/${DEBIAN}:${VERSION}
  script:
    - cp gitlab/debian/planckCoreV3-debug.conf local.conf
    - source /opt/tools/virtualenv/bin/activate
    - make clean
    - make asn1
    - make all -j 4
    - make dbinstall
    - make test -j 4

.debian-release:
  stage: release
  tags:
    - linux
  needs: [debian-test]
  image: ${REGISTRY}/${DEBIAN}:${VERSION}
  script:
    - cp gitlab/debian/planckCoreV3-release.conf local.conf
    - source /opt/tools/virtualenv/bin/activate
    - make clean
    - make asn1
    - make all -j 4
    - make install
    - make dbinstall
    - tar  -C /opt/ -zcvf planckCoreV3.tar.gz planck

debian-release:
  extends: .debian-release
  artifacts:
    paths:
      - planckCoreV3.tar.gz
    expire_in: 2 days
    name: corev3-$CI_COMMIT_BRANCH

debian-tag-release:
  extends: .debian-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG != null
  artifacts:
    paths:
      - planckCoreV3.tar.gz
    expire_in: 6 mos
    name: corev3-$CI_COMMIT_TAG
