# Copyright 2017, pEp Foundation
# This file is part of pEpEngine
# This file may be used under the terms of the GNU General Public License version 3
# see LICENSE.txt


######### General #########
# To use (only) system libraries, set all the *_INC and *_LIB variables to the empty string.
# All the *_INC and *_LIB variables are command line flags, not paths.
# Thus, all *_INC variables' values must start with "-I", and all *_LIB variables' values must start with "-L".

#BUILD_ON:=$(shell uname)

# This variable specifies the platform that the engine should be cross-compiled for.
#BUILD_FOR=$(BUILD_ON)

# Installation path prefix for libraries and binaries, except for system.db
#PREFIX=$(HOME)

# Installation path for system.db
#SYSTEM_DB=/usr/local/share/pEp/system.db

# Filename of the pEpEngine library
#TARGET=libpEpEngine.so


######### C and C++ #########
#TARGET_ARCH=

# The following two variables will be appended to.
# You can thus not set them to a fixed value here.
#LDFLAGS=

#LDLIBS=


######### C #########
#CC=

#CFLAGS=-fPIC -fstrict-aliasing -fdiagnostics-color=always

#CPPFLAGS=

#CFLAGS+= -w -O3 -DNDEBUG

# Additional CFLAGS used for compiling ASN1C-generated code
#CFLAGS_GENERATED=-D_DEFAULT_SOURCE


######### C++ #########
#CXX=g++ -std=gnu++11 -pthread

#CXXFLAGS=-fdiagnostics-color=always -I../src -I../asn.1 $(ETPAN_INC) -w -O3 -DNDEBUG


######### YML2 #########
#YML2_PATH=$(HOME)/yml2

#YML2_PROC=$(YML2_PATH)/yml2proc

#YML2_OPTS=--encoding=utf8


######### asn1c #########
# asn1c binary
#ASN1C=asn1c

# asn1c include search flag
#ASN1C_INC=-I$(HOME)/include


######### libetpan #########
# libetpan library search flag
#ETPAN_LIB=-L$(PREFIX)/lib

# libetpan include search flag
#ETPAN_INC=-I$(PREFIX)/include


######### sqlite3 #########
# If empty (or undefined), compile sqlite3 from the sources shipped with the pEp distribution.
# Otherwise, use an sqlite3 implementation found in the OS's include/library paths.
#SQLITE3_FROM_OS=placeholder


######### OpenPGP #########
# Path of GPG binary
# gpgconf is not available for old version of GPG, for example GPG 2.0.30. Override this variable, if you compile the engine for such an old version.
#GPG_CMD:=$(shell gpgconf --list-components | awk -F: '/^gpg:/ { print $$3; exit 0; }')

# Selects OpenPGP implementation. must be either `GPG` or `NETPGP`
OPENPGP=NETPGP

# Path of libGPGME binary
#LIBGPGME=libgpgme.so.11

# libGPGME library search flag
#GPGME_LIB=

# libGPGME include search flag
#GPGME_INC=

# NETPGP library search flag
#NETPGP_LIB=-L$(PREFIX)/lib

# libGPGME include search flag
#NETPGP_INC=-I$(PREFIX)/include


######### Engine internals #########
# C macros (not environment variables) that can be overridden:
# DEFAULT_KEYSERVER - string with default keyserver
# CRASHDUMP_DEFAULT_LINES - number of log lines to deliver for crashdumps
# Example:
#    EXTRA_MACROS=-DDEFAULT_KEYSERVER=\"default-server.org\" -DCRASHDUMP_DEFAULT_LINES=23
#EXTRA_MACROS=
