#! /bin/sh

# Commit hash header file - if we don't run this, it won't build.
commit_hash="$(git rev-parse HEAD)"
if test -f "templates/commit_hash.h"; then
    sed "s/\(PEP_CURRENT_COMMIT_HASH\ =\).*/\1\"$commit_hash\"/" templates/commit_hash.h > src/commit_hash.h
fi

