DEVICEGROUP

DEFINITIONS AUTOMATIC TAGS EXTENSIBILITY IMPLIED ::=

BEGIN

EXPORTS DeviceGroup-Protocol;
IMPORTS Identity, KeyList, Header FROM PEP;

Beacon ::= SEQUENCE {
    header Header,
    state INTEGER,
    me Identity
}

HandshakeRequest ::= SEQUENCE {
    header Header,
    state INTEGER,
    me Identity,
    partner Identity
}

GroupKeys ::= SEQUENCE {
    header Header,
    state INTEGER,
    me Identity,
    keylist KeyList
}

/* for the tags see end of sync.fsm */

DeviceGroup-Protocol ::= CHOICE {
    beacon [APPLICATION 1] Beacon,
    handshakeRequest [APPLICATION 2] HandshakeRequest,
    groupKeys [APPLICATION 3] GroupKeys
}

END

