DEVICEGROUP
    { iso(1) org(3) dod(6) internet(1) private(4) enterprise(1) pEp (47878) sync(1) keysync(1) }

DEFINITIONS AUTOMATIC TAGS EXTENSIBILITY IMPLIED ::=

BEGIN

EXPORTS DeviceGroup-Protocol;
IMPORTS IdentityList, Header FROM PEP;

Beacon ::= SEQUENCE {

}

HandshakeRequest ::= SEQUENCE {

}

GroupKeys ::= SEQUENCE {
    ownIdentities IdentityList
}

/* for the tags see end of sync.fsm */

DeviceGroup-Protocol ::= SEQUENCE {
    header Header,
    payload CHOICE {
        beacon [APPLICATION 2] Beacon,
        handshakeRequest [APPLICATION 3] HandshakeRequest,
        groupKeys [APPLICATION 4] GroupKeys
    }
}

END

