DEVICEGROUP DEFINITIONS AUTOMATIC TAGS ::=
BEGIN

Beacon ::= SEQUENCE {
    header PEP.Header,
    me PEP.Identity
}

HandshakeRequest ::= SEQUENCE {
    header PEP.Header,
    you PEP.Identity,
    me PEP.Identity
}

OwnKeys ::= SEQUENCE {
    header PEP.Header,
    you PEP.Identity,
    me PEP.Identity,
    keylist PEP.Stringlist
}

Message ::= CHOICE {
    beacon Beacon,
    handshakeRequest HandshakeRequest,
    ownKeys OwnKeys
}

END

