/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "PEP"
 * 	found in "pEp.asn1"
 */

#ifndef	_Header_H_
#define	_Header_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Version.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Header */
typedef struct Header {
	long	 protocol;
	Version_t	 version;
	long	 message;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Header_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Header;

#ifdef __cplusplus
}
#endif

#endif	/* _Header_H_ */
#include <asn_internal.h>
