/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "PEP"
 * 	found in "pEp.asn1"
 */

#ifndef	_Identity_H_
#define	_Identity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <NativeInteger.h>
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Identity */
typedef struct Identity {
	UTF8String_t	 address;
	UTF8String_t	 fpr;
	UTF8String_t	 user_id;
	UTF8String_t	 username;
	long	 comm_type;
	PrintableString_t	 lang;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Identity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Identity;

#ifdef __cplusplus
}
#endif

#endif	/* _Identity_H_ */
#include <asn_internal.h>
