/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "PEP"
 * 	found in "pEp.asn1"
 */

#include "Identity.h"

static int
memb_comm_type_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_comm_type_constr_6 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Identity_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Identity, address),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"address"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Identity, fpr),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fpr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Identity, user_id),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"user-id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Identity, username),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"username"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Identity, comm_type),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_comm_type_constraint_1,
		&asn_PER_memb_comm_type_constr_6,
		0,
		"comm-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Identity, lang),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lang"
		},
};
static ber_tlv_tag_t asn_DEF_Identity_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Identity_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, 0, 0 }, /* comm-type */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 0, 0, 3 }, /* address */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 1, -1, 2 }, /* fpr */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 2, -2, 1 }, /* user-id */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 3, -3, 0 }, /* username */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 5, 0, 0 } /* lang */
};
static asn_SEQUENCE_specifics_t asn_SPC_Identity_specs_1 = {
	sizeof(struct Identity),
	offsetof(struct Identity, _asn_ctx),
	asn_MAP_Identity_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Identity = {
	"Identity",
	"Identity",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Identity_tags_1,
	sizeof(asn_DEF_Identity_tags_1)
		/sizeof(asn_DEF_Identity_tags_1[0]), /* 1 */
	asn_DEF_Identity_tags_1,	/* Same as above */
	sizeof(asn_DEF_Identity_tags_1)
		/sizeof(asn_DEF_Identity_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Identity_1,
	6,	/* Elements count */
	&asn_SPC_Identity_specs_1	/* Additional specs */
};

