PEP
    { iso(1) org(3) dod(6) internet(1) private(4) enterprise(1) pEp(47878) basic(0) }

DEFINITIONS AUTOMATIC TAGS EXTENSIBILITY IMPLIED ::=

BEGIN

EXPORTS Version, Identity, IdentityList;

ISO639-1 ::= PrintableString(FROM ("a".."z")) (SIZE(2))
Hex ::= PrintableString(FROM ("A".."F") | FROM ("0".."9"))
Hash ::= Hex(SIZE(1..128)) -- SHA1 to SHA512 in hex

Identity ::= SEQUENCE {
    address     UTF8String  (SIZE(1..1024)) OPTIONAL,
    fpr         Hash,
    user-id     UTF8String  (SIZE(1..1024)) OPTIONAL,
    username    UTF8String  (SIZE(1..1024)) OPTIONAL,
    comm-type   INTEGER     (0..255) OPTIONAL,
    lang        ISO639-1
}

IdentityList ::= SEQUENCE OF Identity

Version ::= SEQUENCE {
    major       INTEGER (0..255),
    minor       INTEGER (0..255)
}

END

