PEP DEFINITIONS ::=
BEGIN

Identity ::= SEQUENCE {
    address     UTF8String,
    fpr         UTF8String,
    user-id     UTF8String,
    username    UTF8String,
    comm-type   INTEGER (0..255),
    lang        PrintableString (2)
}

Stringlist ::= SEQUENCE OF UTF8String

Version ::= SEQUENCE {
    major       INTEGER (0..255),
    minor       INTEGER (0..255)
}

END

