PEP

DEFINITIONS AUTOMATIC TAGS EXTENSIBILITY IMPLIED ::=

BEGIN

EXPORTS Identity, KeyList, Header;

major-version INTEGER ::= 1
minor-version INTEGER ::= 0

ISO639-1 ::= PrintableString(FROM ("a".."z")) (SIZE(2))
Hex ::= PrintableString(FROM ("A".."F") | FROM ("0".."9"))
Hash ::= Hex(SIZE(1..128)) -- SHA1 to SHA512 in hex

Identity ::= SEQUENCE {
    address     UTF8String  (SIZE(1..1024)) OPTIONAL,
    fpr         Hash,
    user-id     UTF8String  (SIZE(1..1024)) OPTIONAL,
    username    UTF8String  (SIZE(1..1024)) OPTIONAL,
    comm-type   INTEGER     (0..255) OPTIONAL,
    lang        ISO639-1    DEFAULT "en"
}

KeyList ::= SEQUENCE OF Hash

Version ::= SEQUENCE {
    major       INTEGER (0..255) DEFAULT major-version,
    minor       INTEGER (0..255) DEFAULT minor-version
}

Header ::= SEQUENCE {
    version     Version,
    sequence    INTEGER
}

END

