/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "PEP"
 * 	found in "pEp.asn1"
 */

#ifndef	_Stringlist_H_
#define	_Stringlist_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Stringlist */
typedef struct Stringlist {
	A_SEQUENCE_OF(UTF8String_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Stringlist_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Stringlist;

#ifdef __cplusplus
}
#endif

#endif	/* _Stringlist_H_ */
#include <asn_internal.h>
