# Copyright 2020, pEp Foundation
# This file is part of pEpEngine - Android Build
# This file may be used under the terms of the GNU General Public License version 3
# see LICENSE.txt

include ../Makefile.conf

all:
	echo "Placeholder command, this is meant to be cleaned by JNIAdapter Android build"

.PHONY: clean
clean:
	rm -rf include/
