#ifndef COMMIT_HASH_H
#define COMMIT_HASH_H

#define PEP_CURRENT_COMMIT_HASH="ERROR: COMMIT_HASH_NOT_DEFINED. GIT HOOKS NOT IN PLACE FOR CORRECT DISTRIBUTION. CONTACT ADMIN OR PEP FOUNDATION."

#endif

