/**
 * @file      pEp_engine_version.h
 * @brief     machine-generated version information for the pEp Engine
 * @generated by the p≡p Engine ./release script with options
 *            --next-minor-rc --release
 * @license   GNU General Public License 3.0 - see LICENSE.txt
 */
#ifndef _PEP_ENGINE_VERSION_H_
#define _PEP_ENGINE_VERSION_H_

#define PEP_ENGINE_VERSION_MAJOR          3
#define PEP_ENGINE_VERSION_MINOR          2
#define PEP_ENGINE_VERSION_PATCH          0

#define PEP_ENGINE_VERSION_RC             13  /* This is a Release Candidate. */

#define PEP_ENGINE_VERSION_PLUS           +   /* This is a MODIFIED Release Candidate */

/* PEP_ENGINE_VERSION_BRANCH_SUFFIX not defined. */

/* The main version string for the user. */
#define PEP_ENGINE_VERSION "3.2.0-RC13+"

#endif /* #ifndef _PEP_ENGINE_VERSION_H_ */
