/**
 * @file      pEp_engine_version.h
 * @brief     machine-generated version information for the pEp Engine
 * @generated by the p≡p Engine ./release script with options
 *            --next-minor-rc --release
 * @license   GNU General Public License 3.0 - see LICENSE.txt
 */

// 29.08.2023/AT - bumped version to 3.3.2
// 13.09.2023/DZ - bumped version to 3.3.3
// 21.09.2023/AT - bumped version to 3.3.4
// 05.10.2023/AT - bumped version to 3.3.5
// 11.10.2023/AT - bumped version to 3.3.6
// 18.10.2023/IG - bump version to 3.3.7
// 25.10.2023/AT - bumped version to 3.3.8
// 31.10.2023/AT - bumped version to 3.3.9
// 08.11.2023/IG - bump version to 3.3.12
// 10.11.2023/AT - bumped version to 3.3.13
// 13.11.2023/AT - bumped version to 3.3.14

#ifndef _PEP_ENGINE_VERSION_H_
#define _PEP_ENGINE_VERSION_H_

#define PEP_ENGINE_VERSION_MAJOR          3
#define PEP_ENGINE_VERSION_MINOR          3
#define PEP_ENGINE_VERSION_PATCH          14

// #define PEP_ENGINE_VERSION_RC             4   /* This is a Release Candidate. */

/* PEP_ENGINE_VERSION_PLUS not defined: this is an UNmodified Release Candidate. */

/* PEP_ENGINE_VERSION_BRANCH_SUFFIX not defined. */

/* The main version string for the user. */
#define PEP_ENGINE_VERSION "3.3.14"

#endif /* #ifndef _PEP_ENGINE_VERSION_H_ */
